### ISSUE TITLE
Unable to browse in Firefox 60 ESR

### ISSUE THREAD

**Issue by ploq** [studentorkesterfestivalen/sof-react-site#1]
The use of .flat() here kills Edge and Firefox <62. It should be polyfilled.

https://github.com/studentorkesterfestivalen/sof-react-site/blob/e8a471bec1bea355dec65935dbdf890be078ddf8/src/components/PageRouter.js#L100

**Comment by mathiasberggren** [comment]
Anton fixed this long time ago, ty very much for help, very nice.
